global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'auth-service'
  - job_name: 'user-service'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['users-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'user-service'
  - job_name: 'payment-service'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'payment-service'
  - job_name: 'product-service'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['product-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'product-service'
  - job_name: 'order-service'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'order-service'
  

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']