env: "local"

kafka:
  brokers:
    - kafka1:39092
    - kafka2:39093
    - kafka3:39094

grpc_port: 50052

postgres:
  connection: "postgres"
  user: "postgres"
  password: "postgres"
  host: "order-postgres"
  port: "5432"
  name: "order"
  maxPool: 5
  timeout: 1s
  connAttempts: 10

otlp:
  endpoint: tempo:4317

redis:
  password:
  addr: "order-redis:6379"
  poolSize: 2
  minIdleCons: 4
  connTimeout: 1s
