app:
  name: "marketplace"
  version: "1.0.0-local"

kafka:
  brokers:
    - "localhost:9092"

otlp:
  endpoint: "http://localhost:4317"

product_service:
  host: "localhost"
  metrics_port: "7001"

user_service:
  host: "localhost"
  metrics_port: "7002"

payment_service:
  host: "localhost"
  metrics_port: "7003"

auth_service:
  host: "localhost"
  metrics_port: "7004"

env: "local"